##
#"""
#********************************************************************************
#@file       : RelocationThresholds.py
#@brief      : This file contains relocation type tThreshold values
#@author     : Ganesh Pathirakani
#@date(ORG)  : 20 APR 2020
#@copyright  : copyright (C) 2020 SanDisk a Western Digital brand
#********************************************************************************
#"""

#fetch these GC Threshold values using firmware diagnostics

#Relocation Thresholds (hard-coded as of now)
RLC_RANDOM_TRANSFER_LENGTH_LIST = [256, 512, 1024]
RLC_THRESHOLD_SLC_BALANCED = 10
RLC_THRESHOLD_SLC_URGENT   = 6
RLC_THRESHOLD_TLC_BALANCED = 14
RLC_THRESHOLD_TLC_URGENT   = 5

RLC_STATIC_SLC_PEC_VALUE = 1500 # need to check - 2250
RLC_STATIC_TLC_PEC_VALUE = 50 #  need to check - 49


MAX_SOURCE_BLOCK_TO_HOLD_FOR_RELOCATION = 3
NUMBER_OF_TIMES_EPWR_SUCCESS = 4

NUM_OF_FMUS_COPIED_IN_RLC_WRITE_JB_VBA_WP = 48

HOST_WRITE_PF_NEXT_VBA_INJECTION_LENGTH = 16
MTM_WRITE_PF_NEXT_VBA_INJECTION_LENGTH = 16
LOG_WRITE_PF_NEXT_VBA_INJECTION_LENGTH = 16
XOR_WRITE_PF_NEXT_VBA_INJECTION_LENGTH = 16
TLC_RLC_WRITE_PF_NEXT_VBA_INJECTION_LENGTH = NUM_OF_FMUS_COPIED_IN_RLC_WRITE_JB_VBA_WP

#Throttling constants
FE_THROTTLING_QUERY_BOUNDARY_IN_SECTORS = 64 #hardcoded as of now, try to read this value from firmware using diagnostic
FE_EXTRA_NUMBER_OF_RANDOM_TRANSFER_LENGTH_VALUE_IN_SECTORS_TO_GENERATE = 6
RANDOM_TRANSFER_LENGTH_VALUE_IN_SECTORS_TO_GENERATE_RANGE_START_VALUE = 130
RANDOM_TRANSFER_LENGTH_VALUE_IN_SECTORS_TO_GENERATE_RANGE_END_VALUE = 1024

RANDOM_HOST_SLC_BLOCK_TO_WRITE_RANGE_START_VALUE = 5
RANDOM_HOST_SLC_BLOCK_TO_WRITE_RANGE_END_VALUE = 15

TEST_CYCLE_COUNT_RANGE_START_VALUE = 15
TEST_CYCLE_COUNT_RANGE_END_VALUE = 30

STATIC_RELOCATION_RANDOM_SLC_PEC_VALUES = [1000, 2000, 3000, 4000]
STATIC_RELOCATION_RANDOM_TLC_PEC_VALUES = [300, 600, 900]